#!/bin/sh

VMAIL_USER=vmail
VMAIL_ROOT=/var/vmail
VMAIL_UID="$(id -ru $VMAIL_USER)"
VMAIL_GID="$(id -rg $VMAIL_USER)"

MAIL_CONF_DIR=/etc/mail
MAIL_CONF=$MAIL_CONF_DIR/smtpd.conf
CERT_DIR="/etc/letsencrypt/live/$MAIL_DOMAIN"

CREDENTIALS=$MAIL_CONF_DIR/credentials
VIRTUALS=$MAIL_CONF_DIR/virtuals
ALIASES=$MAIL_CONF_DIR/aliases

export MAIL_CONF_DIR MAIL_CONF CERT_DIR CREDENTIALS VIRTUALS ALIASES VMAIL_USER VMAIL_UID VMAIL_GID VMAIL_ROOT